### ISSUE TITLE
ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation`

### ISSUE THREAD

**Issue by barl0g** [philipperemy/deep-learning-bitcoin#21]
localhost:/home/user/deep-learning-bitcoin # docker run -it --name dlb -v $PWD:/app dlb /bin/bash
...
root@820a763c147a:/app# python3 data_generator.py /tmp/btc-trading-patterns/ /tmp/coinbaseUSD.csv 1
Traceback (most recent call last):
  File "data_generator.py", line 14, in <module>
    np.set_printoptions(threshold=np.nan)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/arrayprint.py", line 259, in set_printoptions
    floatmode, legacy)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/arrayprint.py", line 95, in _make_options_dict
    raise ValueError("threshold must be non-NAN, try "
ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

**Comment by barl0g** [comment]
Change
np.set_printoptions(threshold=np.nan)
to
np.set_printoptions(threshold=sys.maxsize)
?

**Comment by mand047** [comment]
same issue

**Comment by programeriss** [comment]
> Change
> np.set_printoptions(threshold=np.nan)
> to
> np.set_printoptions(threshold=sys.maxsize)
> ?

Thanks!
