### ISSUE TITLE
Error while running code

### ISSUE THREAD

**Issue by akriventsev** [philipperemy/deep-learning-bitcoin#4]
I run this command
python3 data_generator.py /tmp/btc-trading-patterns/ /tmp/coinbaseUSD.csv 1

but I get this message

height has been deprecated.

Using: <function generate_quantiles at 0x101d75158>
Reading bitcoin market data file here: /tmp/coinbaseUSD.csv.
Traceback (most recent call last):
  File "data_generator.py", line 94, in <module>
    main()
  File "data_generator.py", line 90, in main
    data_gen_func(data_folder, bitcoin_file)
  File "data_generator.py", line 26, in generate_quantiles
    return generate_cnn_dataset(data_folder, bitcoin_file, get_label)
  File "data_generator.py", line 43, in generate_cnn_dataset
    btc_df = file_processor(bitcoin_file)
  File "/Users/alexanderkirventsev/Documents/bitcoin/deep-learning-bitcoin/data_manager.py", line 13, in file_processor
    p = pd.DataFrame(d['price'].resample('5Min').ohlc())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/generic.py", line 2360, in __getattr__
    (type(self).__name__, name))
AttributeError: 'Series' object has no attribute 'ohlc'

**Comment by philipperemy** [comment]
Be sure to have the latest pandas version

Run something like:

pip install pandas --upgrade

**Comment by akriventsev** [comment]
Thanks a lot

**Comment by philipperemy** [comment]
Welcome :)
