### ISSUE TITLE
Error while running data_generator.py

### ISSUE THREAD

**Issue by maithanhtan** [philipperemy/deep-learning-bitcoin#5]
Hi, Try many time but still get error then running the data_generator.py . Can you help me. 
Thanks
Here is the detail:
Using: <function generate_quantiles at 0x7ffa06e5b0d0>
Reading bitcoin market data file here: /tmp/coinbaseUSD.csv.
--------------------------------------------------------------------------------
Those values should be roughly equal to 1/len(levels):
0 0.100001542282
1 0.100001542282
2 0.0999976865775
3 0.100001542282
4 0.107007356683
5 0.0929918721757
6 0.0999976865775
7 0.100001542282
8 0.0999976865775
9 0.100001542282
IntervalIndex([(-42.016, -0.133], (-0.133, -0.0562], (-0.0562, -0.0234], (-0.0234, -0.00443], (-0.00443, 0.0], (0.0, 0.0111], (0.0111, 0.0312], (0.0312, 0.0646], (0.0646, 0.14], (0.14, 67.889]]
              closed='right',
              dtype='interval[float64]')
--------------------------------------------------------------------------------
/usr/local/lib/python3.4/dist-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The finance module has been deprecated in mpl 2.0 and will be removed in mpl 2.2. Please use the module mpl_finance instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "data_generator.py", line 94, in <module>
    main()
  File "data_generator.py", line 90, in main
    data_gen_func(data_folder, bitcoin_file)
  File "data_generator.py", line 26, in generate_quantiles
    return generate_cnn_dataset(data_folder, bitcoin_file, get_label)
  File "data_generator.py", line 76, in generate_cnn_dataset
    save_to_file(btc_slice, filename=filename)
  File "/root/deep-learning-bitcoin/utils.py", line 29, in save_to_file
    fig, ax = plt.subplots()
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/pyplot.py", line 1202, in subplots
    fig = figure(**fig_kw)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1854, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by philipperemy** [comment]
Your error can be solved by:

https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

**Comment by philipperemy** [comment]
Matplotlib chooses Xwindows backend by default. You need to set matplotlib do not use Xwindows backend.

Add this code to your script and try again:

import matplotlib
matplotlib.use('Agg')


Or add to .config/matplotlib/matplotlibrc line backend : Agg.

**Comment by maithanhtan** [comment]
thanks it work now. Thanks u so much
